services:
  - type: web
    name: ewallet
    buildCommand: NODE_VERSION=20 npm ci && npm run build
    startCommand: npm install -g serve && serve -s build
    env:
        - key: NODE_ENV
          value: production
